name: USB Scanner Project Board

columns:
  - name: To Do
    description: Tasks that need to be done
    automation:
      - status: open
        labels: [enhancement, bug]
  
  - name: In Progress
    description: Tasks currently being worked on
    automation:
      - status: open
        labels: [in-progress]
  
  - name: Review
    description: Tasks that need review
    automation:
      - status: open
        labels: [needs-review]
  
  - name: Done
    description: Completed tasks
    automation:
      - status: closed

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  
  - name: enhancement
    color: a2eeef
    description: New feature or request
  
  - name: in-progress
    color: 0e8a16
    description: Task is being worked on
  
  - name: needs-review
    color: fbca04
    description: Ready for review
  
  - name: documentation
    color: 0075ca
    description: Documentation improvements
  
  - name: help wanted
    color: 008672
    description: Extra attention is needed

